# Generated by Django 4.2.3 on 2025-05-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="component",
            name="operating_current",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=10,
                null=True,
                verbose_name="Робочий струм (A)",
            ),
        ),
        migrations.AddField(
            model_name="component",
            name="operating_voltage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Робоча напруга (V)",
            ),
        ),
        migrations.AddField(
            model_name="component",
            name="package_type",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Тип корпусу"
            ),
        ),
        migrations.AddField(
            model_name="component",
            name="power",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Потужність (W)",
            ),
        ),
    ]
