# Generated by Django 4.2.3 on 2025-05-04 08:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("catalog", "0004_component_operating_current_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="component",
            name="favorited_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="favorite_components",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
