# Generated by Django 4.2.3 on 2025-05-04 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0005_component_favorited_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="component",
            name="image_url",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="Зображення (URL)"
            ),
        ),
    ]
